# -*- coding: utf-8 -*-
"""Basic Plots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BRWwJF603YFY8mLLn-bS_vXmNipXRqTP
"""

# Basic Plots

from google.colab import files

files.upload()



import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns # visualization tool

"""
# Running this will list all files under the specified directory.

import os

for dirname, _, filenames in os.walk('.'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
"""

data = pd.read_csv('USA_cars_datasets.csv')

data.info()

data.corr()

# correlation map
f, ax = plt.subplots(figsize=(18, 18))
sns.heatmap(data.corr(), annot=True, linewidths=.5, fmt='.1f', ax=ax)
plt.show()

data.head()

data.columns

plt.scatter(data.price, data.year, color="red", alpha=0.5)
plt.show()

# Line
data.price.plot(kind='line', color='g', label='price', linewidth=1, alpha=0.5, grid=True)
data.year.plot(kind='line', color='r', label='year', linewidth=1, alpha=0.5, grid=True)

plt.legend(loc='upper right') # legend = puts label into plot
plt.xlabel('x axis') # label = name of label
plt.ylabel('y axis')

plt.title('Line Plot')

plt.show()

# Scatter Plot 
# x = price, y = year columns

data.plot(kind='scatter', x='price', y='year', alpha=0.15, color='black', edgecolor='none')

plt.xlabel('Price')
plt.ylabel('Year')

plt.title('Price Year Scatter Plot')

# Histogram
data.price.plot(kind='hist', color='purple', bins=150, histtype='step', figsize=(10, 10), align='right')

plt.show()

data = pd.read_csv('USA_cars_datasets.csv')

x = data['price']>50000
data[x]

data[(data['price']>50000) & (data['year']>2018)]

